### ISSUE TITLE
Feature request: computed collection on array of docs

### ISSUE THREAD

**Issue by timlrx** [contentlayerdev/contentlayer#81] opened 2021-12-30 09:34 UTC
It would be nice to support the creation of derived objects from `allxxx`. This can be used to create a collection of posts by locale (#14), where the key is the locale and the value and array of posts that match the locale. Another use case would be to create a collection of sorted posts, so one can find the previous and next post easily. 

The API could be similar to `computedFields` but with `resolve` taking an array of docs.

**Comment by schickling** [comment] 2022-01-03 09:53
Very interesting suggestion. This seems like a duplicate of https://github.com/contentlayerdev/contentlayer/issues/71 though?

**Comment by timlrx** [comment] 2022-01-03 10:09
Yes, you're right, I think we are looking for the same feature though naming it differently. Feel free to close this if you would like to reduce duplicate issues.

**Closed** 2022-01-03 10:16 UTC
Labels: duplicate
