### ISSUE TITLE
When the .contentlayer is not automatically generated after installation

### ISSUE THREAD

**Issue by liuliuliucome** [contentlayerdev/contentlayer#410] opened 2023-04-05 06:40 UTC
When the .contentlayer is not automatically generated after installation

<img width="291" alt="image" src="https://user-images.githubusercontent.com/4387324/230000932-4db1e8a0-afd9-4432-90e4-1cb9c0b255c2.png">

**Comment by cibulka** [comment] 2023-04-08 14:34
Possible duplicate of https://github.com/contentlayerdev/contentlayer/issues/415

**Closed** 2023-04-24 14:25 UTC
Labels: duplicate
