### ISSUE TITLE
Importing aliased module

### ISSUE THREAD

**Issue by ashalfarhan** [contentlayerdev/contentlayer#230] opened 2022-05-24 14:09 UTC
I have an issue where I can't import my module with typescript aliases in a Next.js typescript project.

```ts
// contentlayer.config.ts
import type * as H from 'hast';
import {
  makeSource,
  defineDocumentType,
  ComputedFields,
} from 'contentlayer/source-files';
import readingTime from 'reading-time';
import rehypeAutoHeadings from 'rehype-autolink-headings';
import rehypeSlug from 'rehype-slug';
import remarkGfm from 'remark-gfm';
import rehypeShiki from '@re-taro/rehype-shiki';
import { getHighlighter } from 'shiki';
import { getImgProps } from '@site/helpers'; // Here's the module
```

```jsonc
// tsconfig.json
{
  "compilerOptions": {
     // ...other of the config
    "paths": {
      "@site/*": ["./src/*"],
      "@content": ["./.contentlayer/generated"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".contentlayer/generated"
  ],
  "exclude": ["node_modules"]
}
```
`contentlayer` version: `"^0.2.5"`
`next-contentlayer` version: `"^0.2.5"`

When running 
```shell
yarn contentlayer build
```

Here's what I got
<img width="563" alt="Screenshot 2022-05-24 at 21 06 57" src="https://user-images.githubusercontent.com/70800415/170055535-96e86272-963d-453f-8447-103569fdb3c4.png">

Is that possible to use path aliases with typescript to solve this?

Thanks in advance!

**Comment by schickling** [comment] 2022-07-05 14:59
Thanks for opening this issue. Closing as duplicate of #238.

**Closed by schickling** 2022-07-05 14:59 UTC
