### ISSUE TITLE
import { allPosts } from 'contentlayer/generated'; not found

### ISSUE THREAD

**Issue by LTN917** [contentlayerdev/contentlayer#428] opened 2023-04-21 15:36 UTC
I have a question 
I follow the step of "Getting Started" of Contentlayer official website, and I get the error when launching the server

![image](https://user-images.githubusercontent.com/78200429/233677475-41d98908-3197-4767-b459-f2da545f0dee.png)

the reason I guess my compiler want to use 'contentlayer/generated' in node_modules
but the steps don't seem to revise anything in node_modules folder
I'm just learn backend concept in the beginning, so I have no idea to slove this problem

thanks~

**Comment by kingcodefish** [comment] 2023-04-22 03:05
Possible duplicate of https://github.com/contentlayerdev/contentlayer/issues/415

I just had to run `npx contentlayer dev` manually until the issue gets patched.

Others seemed to have gotten `contentlayer dev & next dev` to work as a package.json script, but contentlayer dev doesn't seem to terminate for me properly, so it never reaches the second branch.

**Comment by sean-clayton** [comment] 2023-04-23 23:36
This is indeed a duplicate of #415. I was able to fix this with these lines of code (using the `concurrently` package to fix your issue @kingcodefish)

https://github.com/13vaults/13vaults.com/blob/8a80c8a45dbb464a5a3f7a97ed9d56217527c94a/package.json#L6-L8

**Closed** 2023-04-24 07:50 UTC
