### ISSUE TITLE
Build warning on latest Next.js

### ISSUE THREAD

**Issue by anonrig** [contentlayerdev/contentlayer#475] opened 2023-05-31 18:17 UTC
I'm getting the following build warning when running github.com/ada-url/website

```
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/yagiz/Developer/ada/ada-url.com/node_modules/.pnpm/@contentlayer+core@0.3.3_esbuild@0.17.19_markdown-wasm@1.2.0/node_modules/@contentlayer/core/dist/dynamic-build.js for build dependencies failed at 'import(`file://${compiledConfigPath}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
Generated 10 documents in .contentlayer
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/yagiz/Developer/ada/ada-url.com/node_modules/.pnpm/@contentlayer+core@0.3.3_esbuild@0.17.19_markdown-wasm@1.2.0/node_modules/@contentlayer/core/dist/dynamic-build.js for build dependencies failed at 'import(`file://${compiledConfigPath}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/yagiz/Developer/ada/ada-url.com/node_modules/.pnpm/@contentlayer+core@0.3.3_esbuild@0.17.19_markdown-wasm@1.2.0/node_modules/@contentlayer/core/dist/getConfig/index.js for build dependencies failed at 'import(`file://${modulePath}?x=${Date.now()}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/yagiz/Developer/ada/ada-url.com/node_modules/.pnpm/@contentlayer+core@0.3.3_esbuild@0.17.19_markdown-wasm@1.2.0/node_modules/@contentlayer/core/dist/getConfig/index.js for build dependencies failed at 'import(`file://${modulePath}?x=${Date.now()}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/yagiz/Developer/ada/ada-url.com/node_modules/.pnpm/@contentlayer+core@0.3.3_esbuild@0.17.19_markdown-wasm@1.2.0/node_modules/@contentlayer/core/dist/generation/generate-dotpkg.js for build dependencies failed at 'import(filePathJoin(generatedPkgPath, 'generated', 'index.mjs'))'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/yagiz/Developer/ada/ada-url.com/node_modules/.pnpm/@contentlayer+core@0.3.3_esbuild@0.17.19_markdown-wasm@1.2.0/node_modules/@contentlayer/core/dist/generation/generate-dotpkg.js for build dependencies failed at 'import(filePathJoin(generatedPkgPath, 'generated', 'index.mjs'))'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
```

**Comment by schickling** [comment] 2023-05-31 20:47
Thanks for reporting this issue. I think it's a duplicate of https://github.com/contentlayerdev/contentlayer/issues/272

**Closed by schickling** 2023-05-31 20:47 UTC
