### ISSUE TITLE
Using Nested Objects List in Computed Fields not allowed

### ISSUE THREAD

**Issue by khinshankhan** [contentlayerdev/contentlayer#358] opened 2023-01-21 15:44 UTC
Looking at https://www.contentlayer.dev/docs/reference/source-files/field-types#nested-objects-list I'd like to be able to make computed fields lists strongly typed like that.

Using the example but changing fields to computedFields:
```ts
const Tag = defineNestedType(() => ({
  name: 'Tag',
  fields: {
    title: { type: 'string', required: true },
  },
}))

defineDocumentType(() => ({
  // ...
  computedFields: {
    // ...
    tags: {
      type: 'list',
      of: Tag,
    },
  },
}))
```

I get the following error:
```ts
 fields.tsx    79   7 error    2322   Type '{ type: "list"; of: NestedType<string>; resolve: (doc: GetDocumentTypeGen<T>) => { title: string; }[]; }' is not assignable to type 'ComputedField<T>'.
   Object literal may only specify known properties, and 'of' does not exist in type 'ComputedField<T>'. (lsp)
```

How should I go about strongly typing computed json/ lists?

**Comment by khinshankhan** [comment] 2023-02-03 03:09
My current workaround is declaring the type using typescript instead, eg:
```ts
export interface Computed {
  tags: string[];
  // other fields
}
```
and then in the field, I do something like this:
```ts
    computed: {
      type: "json",
      resolve: (doc) => {
        // ensure unique tags in order 
        const tags = [...new Set((doc?.tags ?? []) as string[])].sort();

        return {
          tags,
          // other fields
        } satisfies Computed;
      },
    },
```

and in the page file, I can use `const computed = page.computed as Computed`. The [satisfies](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html) keyword gives confidence to the later `as Computed`.

**Comment by schickling** [comment] 2023-02-13 13:38
Thanks for opening this issue. This looks like a duplicate of #149. If you think it's a separate issue or have other questions, feel free to follow up in the comments.

**Closed by schickling** 2023-02-13 13:38 UTC
