### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by jahirfiquitiva** [contentlayerdev/contentlayer#144] opened 2022-03-14 18:02 UTC
Hi

I'm trying to update from contentlayer `0.0.34` to `0.1.2` and I'm facing this issue. I already did all the changes mentioned in the release notes

Thanks in advance

```gradle
ConfigReadError {
  error: Error: Package subpath './generated' is not defined by "exports" in /Users/jahir/dev/jahir/website/node_modules/contentlayer/package.json imported from /Users/jahir/dev/jahir/website/.contentlayer/.cache/v0.1.2/compiled-contentlayer-config.mjs
      at new NodeError (node:internal/errors:371:5)
      at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
      at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
      at packageResolve (node:internal/modules/esm/resolve:873:14)
      at moduleResolve (node:internal/modules/esm/resolve:929:18)
      at defaultResolve (node:internal/modules/esm/resolve:1044:11)
      at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
      at link (node:internal/modules/esm/module_job:75:36) {
    code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
  },
  configPath: '/Users/jahir/dev/jahir/website/contentlayer.config.ts',
  _tag: 'ConfigReadError',
  toString: [Function (anonymous)],
  [Symbol()]: {
    error: Error: Package subpath './generated' is not defined by "exports" in /Users/jahir/dev/jahir/website/node_modules/contentlayer/package.json imported from /Users/jahir/dev/jahir/website/.contentlayer/.cache/v0.1.2/compiled-contentlayer-config.mjs
        at new NodeError (node:internal/errors:371:5)
        at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
        at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
        at packageResolve (node:internal/modules/esm/resolve:873:14)
        at moduleResolve (node:internal/modules/esm/resolve:929:18)
        at defaultResolve (node:internal/modules/esm/resolve:1044:11)
        at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
        at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
        at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
        at link (node:internal/modules/esm/module_job:75:36) {
      code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
    },
    configPath: '/Users/jahir/dev/jahir/website/contentlayer.config.ts'
  },
  [Symbol()]: [ 'configPath', 'error' ]
}
```

**Comment by schickling** [comment] 2022-03-14 21:29
Thanks for opening this issue @jahirfiquitiva. Would you mind providing a link to the repository please with reproduction instructions?

**Comment by jahirfiquitiva** [comment] 2022-03-14 21:32
Here's my website repo with a new branch with the changes I did 

https://github.com/jahirfiquitiva/jahir.dev/tree/dep-updates

**Comment by schickling** [comment] 2022-03-14 21:46
Thanks a lot! I've taken a brief look already and will investigate this more thoroughly when I'm back working on Contentlayer towards the end of the month.

My initial findings seem to point to a "circular dependency" problem where in `src/utils/posts.ts` you're importing from `contentlayer/generated` but you're also importing said file indirectly in your `contentlayer.config.ts`. Maybe you can try "untangling" this as a first step? (I'll also try to ignore imports from `contentlayer/generated` in regards to the `contentlayer.config.ts` in future releases.

**Comment by jahirfiquitiva** [comment] 2022-03-14 21:59
> Maybe you can try "untangling" this as a first step?

How can I do that?

**Comment by schickling** [comment] 2022-03-29 15:06
> Here's my website repo with a new branch with the changes I did
> 
> https://github.com/jahirfiquitiva/jahir.dev/tree/dep-updates

Looks like this branch is no longer available. Were you able to resolve your issue? Feel free to ping me on [Discord](https://discord.gg/fk83HNECYJ) as - based on my current understanding - this seems to be a problem in your project and not a problem in Contentlayer.

**Comment by schickling** [comment] 2022-03-29 15:55
I've taken another look at your issue. This will be smoother with the next Contentlayer version but you can already work around it as I've described here for you in this video 🙂 

https://cln.sh/Uypset

As mentioned in the video and above, this is actually not a Contentlayer issue itself, so I'll close this issue for now. Please let me know in case you're running into more problems related to this :)

**Closed by schickling** 2022-03-29 15:55 UTC
Labels: more-info-needed
