### ISSUE TITLE
ERR_IMPORT_ASSERTION_TYPE_MISSING for Node >=16.14.0

### ISSUE THREAD

**Issue by timlrx** [contentlayerdev/contentlayer#153] opened 2022-03-22 22:02 UTC
The generated content collection file - `allxxxx` file, cannot be imported and used directly in a node script for node >= 16.14.0 as [importing JSON modules now requires experimental import assertions syntax](https://github.com/nodejs/node/releases/tag/v16.14.0).

Not sure what's the best workaround as adding the `assert { type: 'json' }` syntax is invalid for Node 14. Alternatively, one could consider generating js files rather than json?

**Comment by schickling** [comment] 2022-03-28 16:48
Oh boy this seems to be yet another (potentially big) Node / ESM friction point. Turns out that the `assert { type: 'json' }` syntax isn't just invalid for Node 14 but also for any Node version `<16.14.0`.

The "best" solution I currently see for this is to provide an "opt-in" configuration option for Contentlayer to include the `assert { type: 'json' }` statements and at some point in the future swap the feature to be default behaviour.

On a second thought I might actually already make this the default behaviour given that Node `16.14.2` is already the default Node LTS version and based on my investigations this only matters when using generated Contentlayer files directly from Node - e.g. Next.js seems to work fine with and without assert type statements.

**Comment by seancdavis** [comment] 2022-03-28 19:52
I think this is a reasonable approach — opt-out vs opt-in. 

There's another option here for the "sensible" default to be contextualized based on the current version of Node running the CL build. If it's pre-16.14, don't write the assertions, otherwise, do it. And the configuration option could override this variable behavior to explicitly add or not add the assertion regardless of the node version.

**Comment by schickling** [comment] 2022-03-29 09:47
That's a really great suggestion @seancdavis. I've just implemented this behaviour (i.e. conditionally adding the `assert { type: 'json' }` if Node 16.14+ is used). For now I won't make this behaviour user-configurable yet but wait until someone is actually facing a problem related to this or has another valid use case for making this configurable.

@timlrx this will be release with the upcoming `0.2.0` release. 🚀

**Comment by schickling** [comment] 2022-03-31 17:32
This was just released as part of the new [`0.2.1` version](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.1). 🚀 

Feel free to comment in case you're running into any problems or open a new issue.

**Closed by schickling** 2022-03-31 17:32 UTC

**Comment by Leyakk** [comment] 2022-04-18 21:51
I've followed the Getting Started guide using Node 16.14+ and I get an error regarding the assert keyword.

**Comment by schickling** [comment] 2022-04-18 22:25
Thanks for your comment. Can you please open a new issue and provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by schickling** [comment] 2022-04-19 13:20
Update: @Leyakk it seems there was indeed another issue related to this when using Node 17 (or newer). This should be fixed now in [`0.2.4`](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.4). :)

**Comment by sidwebworks** [comment] 2022-04-27 08:57
Hi, I am on Node version 16.14.0 and I can confirm this is issue is still there,

I updated to v0.2.4 of the package, and cleared all cache and node_modules just to cross check.

However it still generates the assert statements,

here is the `_index.mjs`

```js
// NOTE This file is auto-generated by Contentlayer

import firstMdx from './first.mdx.json' assert { type: 'json' };

export const allPosts = [firstMdx];

```

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/58144379/165481496-ded1dbd5-2034-47ac-8bf3-a1ede9c759ef.png">


Removing the assert fixes the error for me.

**Comment by chopfitzroy** [comment] 2022-05-10 05:58
I am seeing a slightly different error (was building fine yesterday).

```
TypeError: Cannot read properties of undefined (reading 'cwd')
```

Have tried:
- Updating content layer (`0.2.4`)
- Updating Next (`12.1.5`)
- Node `16.13`
- Node `16.14`
- Node `17.9`

Cannot get any combination of the above to resolve the issue.

Have also tried nuking the `node_modules/` and `.contentlayer` directory as well.
