### ISSUE TITLE
Document Collection Manifest Generator generates duplicate import names for Korean file names

### ISSUE THREAD

**Issue by Likilee** [contentlayerdev/contentlayer#375] opened 2023-02-09 12:44 UTC
## 

It seems that there is a problem with the Document Collection Manifest generator. When using a file name in Korean, the generator is unable to create an appropriate import name, so it creates an import name based on the first alphabet of the extension. This causes an issue by creating a duplication of the import name.

```ts
// NOTE This file is auto-generated by Contentlayer
import test23Md from './test23.md.json' assert { type: 'json' }
import mdx from './개발자 키리 - 대한민국 최애 개발자.mdx.json' assert { type: 'json' }
import mdx from './테스트용마크다운.mdx.json' assert { type: 'json' }
import 2____mMdx from './한글2____m.mdx.json' assert { type: 'json' }

export const allPosts = [helloWorldMd, test23Md, mdx, mdx, 2____mMdx]
```

## Screen shot
_**My content directory**_
<img width="345" alt="image" src="https://user-images.githubusercontent.com/35288028/217815995-04146a97-2cec-4dc4-a27e-484ab6aeeab2.png">

**_Auto generated 'document collection manifest'_**
![image](https://user-images.githubusercontent.com/35288028/217815782-003d5dac-a0f1-42ba-ab56-936d59aa6a80.png)

**Comment by schickling** [comment] 2023-02-13 13:26
Thanks for opening this issue. This looks like a duplicate of #337. If you think it's a separate issue or have other questions, feel free to follow up in the comments.

**Closed by schickling** 2023-02-13 13:26 UTC
