### ISSUE TITLE
Can't use nested type in computed fields

### ISSUE THREAD

**Issue by seancdavis** [contentlayerdev/contentlayer#419] opened 2023-04-11 19:42 UTC
I have a field that will be computed and I want to return a specific object shape with an associated type.

For example:

```ts
export const Post = defineDocumentType(() => ({
  name: "Post",
  images: {
    type: "list",
    of: { type: "string" },
  },
  computedFields: {
    processedImages: {
      type: "list",
      of: {
        type: "nested",
        of: Image, // referencing a defined nested type
      },
    },
  },
}));
```

I'm currently working around this by transforming the images and writing my own types in the project code. These types inherit from Contentlayer types.

**Comment by schickling** [comment] 2023-04-24 14:36
Duplicate of #149

**Closed by schickling** 2023-04-24 14:36 UTC
