### ISSUE TITLE
Ability to add Typescript types to our defined document types?

### ISSUE THREAD

**Issue by cobbvanth** [contentlayerdev/contentlayer#492] opened 2023-06-19 21:15 UTC
I am currently using the json type when defining my document with `defineDocumentType`, however this generates to an `any` type, causing pain inside of the actual app. Would it be possible to pass in Typescript interfaces/types in the future to alleviate this?

thanks

**Comment by schickling** [comment] 2023-06-19 21:47
Duplicate of https://github.com/contentlayerdev/contentlayer/issues/26

**Closed by schickling** 2023-06-19 21:47 UTC
