### ISSUE TITLE
 next-contentlayer installation ERROR in next 14.0.3 on terminal

### ISSUE THREAD

**Issue by Sahad-09** [contentlayerdev/contentlayer#605] opened 2023-11-20 15:29 UTC
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mirsazzathossain.me@0.1.0
npm ERR! Found: next@14.0.3
npm ERR! node_modules/next
npm ERR!   next@"14.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12 || ^13" from next-contentlayer@0.3.4
npm ERR! node_modules/next-contentlayer
npm ERR!   next-contentlayer@"^0.3.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! 
npm ERR! For a full report see:
npm ERR! C:\Users\Sahad\AppData\Local\npm-cache\_logs\2023-11-23T07_19_34_982Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\Sahad\AppData\Local\npm-cache\_logs\2023-11-23T07_19_34_982Z-debug-0.log

![image](https://github.com/contentlayerdev/contentlayer/assets/91364349/f9e090c0-4a1e-40b2-977e-cc7d9ce1e808)

**This error does not appear when I changed the version to next 13**

**Comment by Sahad-09** [comment] 2023-11-21 03:13
@anthonyverducci change the next version to 13.4 it works

**Comment by z4nr34l** [comment] 2023-11-22 07:09
@Sahad-09 the point is to use latest possible version - I've made a working (throwing warnings but working) setup with latest next and contentlayer, just force the installation

**Comment by Sahad-09** [comment] 2023-11-22 08:01
@z4nr34l i see, Did people stop maintaining this repo ? It seems to be months ago so there might be some bug.

**Comment by mkelley33** [comment] 2023-11-22 12:52
I would also like to see support for Next.js 14 without having to force the installation.

**Comment by fraune** [comment] 2023-11-23 05:31
This issue is a dupe of #575 

In the meantime, try `npm install --force`

**Comment by piotrszubert** [comment] 2023-11-24 11:40
add this in your package.json and then try install once again

```
"overrides": {
    "next-contentlayer": {
      "next": "$next"
    }
  },
```

**Comment by kachkaev** [comment] 2023-11-24 23:33
Duplicate of #575. Resolvable by https://github.com/contentlayerdev/contentlayer/pull/576

**Closed** 2023-11-25 01:58 UTC
