### ISSUE TITLE
NextJS relative image imports

### ISSUE THREAD

**Issue by SamuelQuinones** [contentlayerdev/contentlayer#289] opened 2022-08-14 01:55 UTC
Hi, I've been trying to figure out if its possible for image imports to resolve relative to a nested directory, let me explain:

I have the following structure
![image](https://user-images.githubusercontent.com/51345689/184518841-4fe15425-6dad-4248-950d-80e2e8f1c03c.png)

where posts will be stored in a named directory, with an index file and any other resources

And in the `index.mdx` file for "building-a-blog" I want add the dummy.png image,  So i'm trying this:
![image](https://user-images.githubusercontent.com/51345689/184518862-2949c028-b236-4dd5-9053-b3ff461ff353.png)

it wasn't working, but when doing research I saw that it looked like some kind of fix for this was put in place in the most recent release as part of #270 but I couldn't quite figure out how to get it to work,

I tried updating my `makeSource` function with an `esbuildOptions` function:

```ts
export default makeSource({
  contentDirPath: "_posts",
  documentTypes: [Post],
  mdx: {
    esbuildOptions: (options) => {
      options.loader = {
        ...options.loader,
        ".png": "dataurl",
      };
      return options;
    },
    remarkPlugins: [remarkMdxImages],
  },
});
```
and tried using the remarkMdxImages plugin as it seemed that's what most people were doing

When i do this, I get an error in the console:
![image](https://user-images.githubusercontent.com/51345689/184518982-f6043d48-b1db-4fe0-bca0-68c050f62731.png)

I don't know if I'm missing something, or if the fix mentioned in #270 was for something completely different

Theres nothing special about the project either, it uses https://github.com/SamuelQuinones/samtheq.com with the example additions from the getting started documentation.

**Comment by SamuelQuinones** [comment] 2022-08-14 01:58
I should also note that when I try to reference an image in the public directory:
![image](https://user-images.githubusercontent.com/51345689/184519379-16e5e67b-1bee-4bd9-aff6-c92a6f1dc165.png)

it renders on the page just fine

**Comment by schickling** [comment] 2022-09-05 13:09
Thanks a lot for opening this issue. This seems to be a duplicate of https://github.com/contentlayerdev/contentlayer/issues/11.

In case you think it's a different issue, I'm happy to re-open this issue.

**Closed by schickling** 2022-09-05 13:09 UTC
