### ISSUE TITLE
 Package path ./generated is not exported from package

### ISSUE THREAD

**Issue by Nithur-M** [contentlayerdev/contentlayer#510] opened 2023-07-15 07:38 UTC
I had to add this to package.json because I am unable to use latest version: 
```
"npm": {
    "overrides": {
        "@opentelemetry/api": "1.4.1",
        "@opentelemetry/core": "1.13.0",
        "@opentelemetry/exporter-trace-otlp-grpc": "0.39.1",
        "@opentelemetry/resources": "1.13.0",
        "@opentelemetry/sdk-trace-base": "1.13.0",
        "@opentelemetry/sdk-trace-node": "1.13.0",
        "@opentelemetry/semantic-conventions": "1.13.0"
    }
}
```
Then the above error popped up. I have followed the guide on getting started section. Anyone facing this issue?
I am using nextjs 13.4.10 with app router.

**Comment by nkilm** [comment] 2023-07-15 16:13
Which OS are you using?

**Comment by Nithur-M** [comment] 2023-07-15 16:15
Windows 10, why?

**Comment by schickling** [comment] 2023-07-17 13:44
Duplicate of #506

**Closed by schickling** 2023-07-17 13:44 UTC
